/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversitiesSlugRouteImport } from './routes/universities.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AdminMetricsRouteImport } from './routes/admin.metrics'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminAvailabilityRouteImport } from './routes/admin.availability'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin.applications.$id'
import { Route as AuthenticatedDashboardShortlistRouteImport } from './routes/_authenticated/dashboard/shortlist'
import { Route as AuthenticatedDashboardReferralsRouteImport } from './routes/_authenticated/dashboard/referrals'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard/messages'
import { Route as AuthenticatedDashboardDocumentsRouteImport } from './routes/_authenticated/dashboard/documents'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard/bookings'
import { Route as AuthenticatedDashboardApplicationsRouteImport } from './routes/_authenticated/dashboard/applications'
import { Route as AuthenticatedDashboardApplicationsIdRouteImport } from './routes/_authenticated/dashboard/applications.$id'
import { Route as AuthenticatedDashboardApplicationsIdSubmitRouteImport } from './routes/_authenticated/dashboard/applications.$id.submit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesSlugRoute = UniversitiesSlugRouteImport.update({
  id: '/universities/$slug',
  path: '/universities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminApplicationsRoute,
} as any)
const AuthenticatedDashboardShortlistRoute =
  AuthenticatedDashboardShortlistRouteImport.update({
    id: '/shortlist',
    path: '/shortlist',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReferralsRoute =
  AuthenticatedDashboardReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDocumentsRoute =
  AuthenticatedDashboardDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardApplicationsRoute =
  AuthenticatedDashboardApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardApplicationsIdRoute =
  AuthenticatedDashboardApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardApplicationsRoute,
  } as any)
const AuthenticatedDashboardApplicationsIdSubmitRoute =
  AuthenticatedDashboardApplicationsIdSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => AuthenticatedDashboardApplicationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRouteWithChildren
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/shortlist': typeof AuthenticatedDashboardShortlistRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/dashboard/applications/$id': typeof AuthenticatedDashboardApplicationsIdRouteWithChildren
  '/dashboard/applications/$id/submit': typeof AuthenticatedDashboardApplicationsIdSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRouteWithChildren
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/shortlist': typeof AuthenticatedDashboardShortlistRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/dashboard/applications/$id': typeof AuthenticatedDashboardApplicationsIdRouteWithChildren
  '/dashboard/applications/$id/submit': typeof AuthenticatedDashboardApplicationsIdSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/_authenticated/dashboard/applications': typeof AuthenticatedDashboardApplicationsRouteWithChildren
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/_authenticated/dashboard/shortlist': typeof AuthenticatedDashboardShortlistRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/_authenticated/dashboard/applications/$id': typeof AuthenticatedDashboardApplicationsIdRouteWithChildren
  '/_authenticated/dashboard/applications/$id/submit': typeof AuthenticatedDashboardApplicationsIdSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cookies'
    | '/courses'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/dashboard'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/leads'
    | '/admin/metrics'
    | '/courses/$slug'
    | '/universities/$slug'
    | '/dashboard/applications'
    | '/dashboard/bookings'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/referrals'
    | '/dashboard/shortlist'
    | '/admin/applications/$id'
    | '/dashboard/applications/$id'
    | '/dashboard/applications/$id/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cookies'
    | '/courses'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/dashboard'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/leads'
    | '/admin/metrics'
    | '/courses/$slug'
    | '/universities/$slug'
    | '/dashboard/applications'
    | '/dashboard/bookings'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/referrals'
    | '/dashboard/shortlist'
    | '/admin/applications/$id'
    | '/dashboard/applications/$id'
    | '/dashboard/applications/$id/submit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/cookies'
    | '/courses'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/dashboard'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/leads'
    | '/admin/metrics'
    | '/courses/$slug'
    | '/universities/$slug'
    | '/_authenticated/dashboard/applications'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/documents'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/referrals'
    | '/_authenticated/dashboard/shortlist'
    | '/admin/applications/$id'
    | '/_authenticated/dashboard/applications/$id'
    | '/_authenticated/dashboard/applications/$id/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  UniversitiesSlugRoute: typeof UniversitiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$slug': {
      id: '/universities/$slug'
      path: '/universities/$slug'
      fullPath: '/universities/$slug'
      preLoaderRoute: typeof UniversitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
    '/_authenticated/dashboard/shortlist': {
      id: '/_authenticated/dashboard/shortlist'
      path: '/shortlist'
      fullPath: '/dashboard/shortlist'
      preLoaderRoute: typeof AuthenticatedDashboardShortlistRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/referrals': {
      id: '/_authenticated/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof AuthenticatedDashboardReferralsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/documents': {
      id: '/_authenticated/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/applications': {
      id: '/_authenticated/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof AuthenticatedDashboardApplicationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/applications/$id': {
      id: '/_authenticated/dashboard/applications/$id'
      path: '/$id'
      fullPath: '/dashboard/applications/$id'
      preLoaderRoute: typeof AuthenticatedDashboardApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardApplicationsRoute
    }
    '/_authenticated/dashboard/applications/$id/submit': {
      id: '/_authenticated/dashboard/applications/$id/submit'
      path: '/submit'
      fullPath: '/dashboard/applications/$id/submit'
      preLoaderRoute: typeof AuthenticatedDashboardApplicationsIdSubmitRouteImport
      parentRoute: typeof AuthenticatedDashboardApplicationsIdRoute
    }
  }
}

interface AuthenticatedDashboardApplicationsIdRouteChildren {
  AuthenticatedDashboardApplicationsIdSubmitRoute: typeof AuthenticatedDashboardApplicationsIdSubmitRoute
}

const AuthenticatedDashboardApplicationsIdRouteChildren: AuthenticatedDashboardApplicationsIdRouteChildren =
  {
    AuthenticatedDashboardApplicationsIdSubmitRoute:
      AuthenticatedDashboardApplicationsIdSubmitRoute,
  }

const AuthenticatedDashboardApplicationsIdRouteWithChildren =
  AuthenticatedDashboardApplicationsIdRoute._addFileChildren(
    AuthenticatedDashboardApplicationsIdRouteChildren,
  )

interface AuthenticatedDashboardApplicationsRouteChildren {
  AuthenticatedDashboardApplicationsIdRoute: typeof AuthenticatedDashboardApplicationsIdRouteWithChildren
}

const AuthenticatedDashboardApplicationsRouteChildren: AuthenticatedDashboardApplicationsRouteChildren =
  {
    AuthenticatedDashboardApplicationsIdRoute:
      AuthenticatedDashboardApplicationsIdRouteWithChildren,
  }

const AuthenticatedDashboardApplicationsRouteWithChildren =
  AuthenticatedDashboardApplicationsRoute._addFileChildren(
    AuthenticatedDashboardApplicationsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardApplicationsRoute: typeof AuthenticatedDashboardApplicationsRouteWithChildren
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardDocumentsRoute: typeof AuthenticatedDashboardDocumentsRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardReferralsRoute: typeof AuthenticatedDashboardReferralsRoute
  AuthenticatedDashboardShortlistRoute: typeof AuthenticatedDashboardShortlistRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardApplicationsRoute:
      AuthenticatedDashboardApplicationsRouteWithChildren,
    AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
    AuthenticatedDashboardDocumentsRoute: AuthenticatedDashboardDocumentsRoute,
    AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
    AuthenticatedDashboardReferralsRoute: AuthenticatedDashboardReferralsRoute,
    AuthenticatedDashboardShortlistRoute: AuthenticatedDashboardShortlistRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminApplicationsRouteChildren {
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
}

const AdminApplicationsRouteChildren: AdminApplicationsRouteChildren = {
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
}

const AdminApplicationsRouteWithChildren =
  AdminApplicationsRoute._addFileChildren(AdminApplicationsRouteChildren)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMetricsRoute: AdminMetricsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CookiesRoute: CookiesRoute,
  CoursesRoute: CoursesRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  UniversitiesSlugRoute: UniversitiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
